# Generated by Django 3.1.7 on 2021-02-27 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year', models.IntegerField(default=4)),
            ],
        ),
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_type', models.CharField(choices=[('regular', 'regular'), ('paid', 'paid')], max_length=100)),
                ('girl_seat', models.IntegerField(default=0)),
                ('tribe_seat', models.IntegerField(default=0)),
                ('other_seat', models.IntegerField()),
                ('total_fee', models.FloatField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.course')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=100)),
                ('address', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('rank', models.IntegerField()),
                ('roll_no', models.CharField(default='', max_length=50, unique=True)),
                ('tribe', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SelectionOnCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.coursecategory')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.student')),
            ],
        ),
        migrations.CreateModel(
            name='ChooseCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('select', models.BooleanField(default=False)),
                ('priority', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('course_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.coursecategory')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student')),
            ],
            options={
                'unique_together': {('priority', 'student')},
            },
        ),
    ]
