# Generated by Django 3.1.7 on 2021-02-27 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectiononcourse',
            name='girl_priorty',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='selectiononcourse',
            name='tribe_priority',
            field=models.BooleanField(default=False),
        ),
    ]
